# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Resolve dependencies
      run: mvn dependency:resolve
    - name: Build with Maven
      run: |
        mvn -DskipTests package
    - name: Rename
      working-directory: ./target/
      run: |
        mv tokens.json.sample tokens.json
        mv options.json.sample options.json
        mv Tweet-Deleter-1.0-SNAPSHOT-jar-with-dependencies.jar tweet-delete.jar
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: tweet-delete
        retention-days: 10
        path: |
          ./target/tokens.json
          ./target/options.json
          ./target/tweet-delete.jar
